[seller]
name = "Jane Doe"
tagline = "Graphic Designer"

[invoice]
decimals = 2
show-subtotal = true
date-format = "%d %b %Y"
tax-columns = ["CGST", "SGST", "IGST"]
discount-column = "discount"
style-color = "#f7e6e4"

[receipt]
decimals = 2
date-format = "%d %b %Y"
style-color = "#f7e6e4"

[signature]
prefix = "Thank You!"
# text = "Best regards,\nJane Doe"

[payment]
payment-methods-text = "Pay via UPI/Cash"
currency = "INR"

[payment.upi]
upi-id = "1234567890@upi"
bottom-note = "Scan the above QR code to pay via UPI"
include-link = true
include-amount = true
transaction-note = "Payment for invoice {INVOICE_NUMBER}"

[footer]
text = """
GSTIN: **123456789**

__All amounts are in INR.__
__This is a computer-generated document and does not require a signature.__
"""

[excel]
filepath = "examples/sample.xlsx"

[output.combined]
path = "examples/output/combined.pdf"
type = "combined"            # combined, individual, or clients
start-date = "2025-01-01"
end-date = "2025-12-31"
include-summary = true


[output.individual]
path = "examples/output/individuals/{NUMBER}.pdf"
type = "individual"

[output.clients]
type = "clients"
path = "examples/output/clients/{CLIENT}.pdf"
start-date = "2025-01-01"
include-summary = true
